name: CI

on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:
  build-and-test:
    name: Build & Test

    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64

    runs-on: "${{ matrix.os }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build project
        run: dotnet build src/Murder.Editor

      - name: Run unit tests
        run: dotnet test src/Murder.Tests
